version: '3.8'

services:
  # Agent Factory Process
  aos-agent-factory:
    build: .
    environment:
      - PROCESS_ID_TO_MONITOR=AyM7Y57xDnioSDsfkdKMWCZ8FaaqJOYbR5XYDy_F-IU
      - PORT=3001
      - SU_URL=https://su-router.ao-testnet.xyz
      - MESSAGE_POLLING_INTERVAL=10s
    networks:
      - aos-network

  # Permaweb Index Process
  aos-permaweb-index:
    build: .
    environment:
      - PROCESS_ID_TO_MONITOR=SzooQdJ_y0h9aRreZTIE5EGwkDuLvaR4qnjJztPumPo
      - PORT=3002
      - SU_URL=https://su-router.ao-testnet.xyz
      - MESSAGE_POLLING_INTERVAL=10s
    networks:
      - aos-network

  # Dexi Process
  aos-dexi:
    build: .
    environment:
      - PROCESS_ID_TO_MONITOR=UNjNaSFkjRH5hGOvQ7YCYVu_q7HLwjtv0d50Bp9vGNo
      - PORT=3003
      - SU_URL=https://su-router.ao-testnet.xyz
      - MESSAGE_POLLING_INTERVAL=10s
    networks:
      - aos-network
    deploy:
      replicas: 4

  # Token Locker Process
  aos-token-locker:
    build: .
    environment:
      - PROCESS_ID_TO_MONITOR=H0iGy5TgV_7ckTPB1COxwtOz2muCJqiXz_p_W0P0xN8
      - PORT=3005
      - SU_URL=https://su-router.ao-testnet.xyz
      - MESSAGE_POLLING_INTERVAL=10s
    networks:
      - aos-network

  # Permaweb Index Token Process
  aos-permaweb-index-token:
    build: .
    environment:
      - PROCESS_ID_TO_MONITOR=ashzRmPuxsO6xSZulIeZl-rQ-DsFsjwLYc8IIlY-Ots
      - PORT=3006
      - SU_URL=https://su-router.ao-testnet.xyz
      - MESSAGE_POLLING_INTERVAL=10s
    networks:
      - aos-network

  # Registry Process
  aos-registry:
    build: .
    environment:
      - PROCESS_ID_TO_MONITOR=ju7evX0oEl4X1W7-3gxsq4uMdjUOHXYMUp_VvWgw90k
      - PORT=3007
      - SU_URL=https://su-router.ao-testnet.xyz
      - MESSAGE_POLLING_INTERVAL=10s
    networks:
      - aos-network

  # Wrapped AR Process
  aos-wrapped-ar:
    build: .
    environment:
      - PROCESS_ID_TO_MONITOR=SdykGZN16NdQrbPyIJSipet6_c0pIjFFIRDXkJkZFK8
      - PORT=3008
      - SU_URL=https://su-router.ao-testnet.xyz
      - MESSAGE_POLLING_INTERVAL=10s
    networks:
      - aos-network

  # Token Factory Process
  aos-token-factory:
    build: .
    environment:
      - PROCESS_ID_TO_MONITOR=qH76V-hcgOXQuyQ5mbUfa7J2o0FK8p_rgLBcQb45tLQ
      - PORT=3010
      - SU_URL=https://su-router.ao-testnet.xyz
      - MESSAGE_POLLING_INTERVAL=10s
    networks:
      - aos-network

  # Portfolio Agent Factory Process
  aos-portfolio-agent-factory:
    build: .
    environment:
      - PROCESS_ID_TO_MONITOR=vKVhuEP-dbwi7CA7Ca1_PcIDgtFprE_tYxe7x-GR2-A
      - PORT=3011
      - SU_URL=https://su-router.ao-testnet.xyz
      - MESSAGE_POLLING_INTERVAL=10s
    networks:
      - aos-network

  # FLP Factory Process
  aos-flp-factory:
    build: .
    environment:
      - PROCESS_ID_TO_MONITOR=JC0_BVWWf7xbmXUeKskDBRQ5fJo8fWgPtaEYMOf-Vbk
      - PORT=3012
      - SU_URL=https://su-router.ao-testnet.xyz
      - MESSAGE_POLLING_INTERVAL=10s
      - LOAD_FROM_SCRATCH=true
      - LOAD_FROM_CHECKPOINT=false
      - DRY_RUN_STRATEGY=clone
    networks:
      - aos-network

  # AMM Factory Process
  aos-amm-factory:
    build: .
    environment:
      - PROCESS_ID_TO_MONITOR=50U3BcLrRF2Bq51eeJdVdoMzrQMgjCeVai7LWY4Wm_s
      - PORT=3013
      - SU_URL=https://su-router.ao-testnet.xyz
      - MESSAGE_POLLING_INTERVAL=10s
    networks:
      - aos-network

  # Payment Token Process
  aos-payment-token:
    build: .
    environment:
      - PROCESS_ID_TO_MONITOR=atlyT9ph8ex_TxDDkQ2fdbhVT62sLw6boJPdEr7UqJE
      - PORT=3014
      - SU_URL=https://su-router.ao-testnet.xyz
      - MESSAGE_POLLING_INTERVAL=10s
    networks:
      - aos-network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.staging.conf:/etc/nginx/nginx.conf:ro # Point to staging nginx config
    depends_on:
      - aos-agent-factory
      - aos-permaweb-index
      - aos-dexi
      - aos-token-locker
      - aos-permaweb-index-token
      - aos-registry
      - aos-wrapped-ar
      - aos-token-factory
      - aos-portfolio-agent-factory
      - aos-flp-factory
      - aos-amm-factory
      - aos-payment-token
    networks:
      - aos-network

networks:
  aos-network:
    driver: bridge
