global:
  scrape_interval: 15s

scrape_configs:
  - job_name: traefik
    static_configs:
      - targets: ["traefik:9100"]

  - job_name: node
    static_configs: [{ targets: ["node-exporter:9100"] }]

  - job_name: cadvisor
    metrics_path: /metrics      # default, but spell it out
    static_configs:
      - targets: ["cadvisor:8081"]
      
  - job_name: docker
    static_configs:
      - targets: ["docker-exporter:9417"]