apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    url: http://prometheus:9090        # <-- change if your Prom container differs
    access: proxy
    isDefault: true